### ISSUE TITLE
ShaderMeshTerrain does not work with RenderPipeline

### ISSUE THREAD

**Issue by typewriter1** [tobspr/RenderPipeline#101]
When using RenderPipeline together with ShaderMeshTerrain, the Panda3D window fails to open, without even giving an error message. The same code for ShaderMeshTerrain works perfectly when I comment out the RenderPipeline code.

**Comment by tobspr** [comment]
Have you checked https://github.com/tobspr/RenderPipeline-Samples/blob/master/08-Terrain/main.py ? This is an example showing how to use it with the RP.

**Comment by typewriter1** [comment]
Adding the load_prc_file_data lines from the sample, and setting the effect to effects/terrain_effect fixes the problem. Thanks
