### ISSUE TITLE
Mac OSX -  fail to install

### ISSUE THREAD

**Issue by mvaranda** [tobspr/RenderPipeline#108]
Hello All,

I am just getting started and could not run the installer. Not sure if my NVIDIA GTX 775M indeed does not support the desired shaders or any other bug:

```
Marcelos-iMac:render_pipeline mvaranda$ python setup.py 
-------------------------------------------------------------------------------
Render Pipeline Setup 1.3
-------------------------------------------------------------------------------
[ 01 ]  Checking Panda3D Modules
[ 02 ]  Checking requirements ..
	Running script: data/setup/check_requirements.py

ERROR: Compute shaders not supported! Please update your driver, or get a newer gpu.

Failed to execute 'check_requirements.py'
Output: Command '['/usr/bin/python', '-B', 'check_requirements.py']' returned non-zero exit status 1 
 
It seems the setup failed, do you want to open the troubleshooting page for this step? (y/n): 

```
![screen shot 2018-12-17 at 8 03 59 am](https://user-images.githubusercontent.com/4267257/50089042-b7cdf980-01d2-11e9-8002-38018f5ee2f4.png)

**Comment by rdb** [comment]
macOS does not support compute shaders, because Apple makes the OpenGL drivers and they are trying to push their walled-garden Metal API instead. :frowning_face:

**Comment by mvaranda** [comment]
Sad thing... thanks for the quick reply.

**Comment by romantolkachyov** [comment]
Is it possible to make some kind of fallback? To make it possible to develop under OSX.

**Comment by rdb** [comment]
No, Apple just doesn't support the latest version of OpenGL.  Getting access to compute shaders on macOS would therefore require Panda3D to gain support for Vulkan or Metal.

@mvaranda this should work on macOS even though it does not even come close to offering the full scope of things supported by RenderPipeline:
https://github.com/Moguri/panda3d-simplepbr

**Comment by tobspr** [comment]
Closing since no solution is possible
