### ISSUE TITLE
Vertex Coloring

### ISSUE THREAD

**Issue by drewc5131** [tobspr/RenderPipeline#110]
Models i am trying to use have vertex coloring, along with node.setColor() in the code, I am having difficulties getting this to work with the effect yaml. 

Normally you would have an out coming from vertex with the vert color, and an input in the frag shader that takes that in, but that doesn't seem to be applying properly. 

This is my current yaml file.
```yaml
vertex:
    inout: |
        in vec4 p3d_Color;
        out vec4 m_color;
    material: |
        m_color = p3d_Color;
fragment:
    inout: |
        in vec4 m_color;
    material: |
        m.shading_model = SHADING_MODEL_DEFAULT;
        m.basecolor = m_color * texture(p3d_Texture0, texcoord);
        m.roughness = 0.9;
        m.specular_ior = 1.51;
        m.metallic = 0;
        m.normal = vOutput.normal;
        m.shading_model_param0 = 0.0; // unused

```

**Comment by tobspr** [comment]
From a quick look, this seems like it should work.  What exactly does not work? The color is not multiplied with the texture?

FYI, instead of sampling p3d_Texture0 manually, simply use `sampled_diffuse.xyz`

You can also have a look at 
https://github.com/tobspr/RenderPipeline/blob/master/rpcore/shader/templates/gbuffer.frag.glsl#L152

(The `material:` section will be inserted at the `%material%`)

to see which variables are available there

**Comment by drewc5131** [comment]
> From a quick look, this seems like it should work.

Exactly, it should. Looking at shaders ive used without the render pipeline, thats exactly how it's setup, and it works. 

Note that I don't have individual materials, this is a global set_effect() yaml file. That file based off of the one from Roaming Ralph in the render pipeline samples repo.

> What exactly does not work? The color is not multiplied with the texture?

Yeah, the object ends up showing as the basic texture version, not colored.

> FYI, instead of sampling p3d_Texture0 manually, you can simply use `sampled_diffuse.xyz`

That was just copied from roaming ralphs example, since I am in the same boat as not having any materials, so i just used that example, thanks for the info

As a side note, I also seem to have an issue where the screen is completely black everytime i load a new area, and i have to just resize the window to fix it.

**Comment by drewc5131** [comment]
_I was editing the wrong file oh my god_

i had a copy of it in an incorrect location so i copied it to the new one, but i never opened the new one in np++ and didnt realize haha
This is my final one, for reference if anyone wants

```yaml
vertex:
    inout: |
        in vec4 p3d_Color;
        out vec4 m_color;
    transform: |
        m_color = p3d_Color;
fragment:
    inout: |
        in vec4 m_color;
    material: |
        m.shading_model = SHADING_MODEL_DEFAULT;
        m.basecolor = m_color.xyz * sampled_diffuse.xyz;
        m.roughness = 0.9;
        m.specular_ior = 1.51;
        m.metallic = 0;
        m.normal = vOutput.normal;
        m.shading_model_param0 = 0.0; // unused
```

**Comment by tobspr** [comment]
Oh, awesome! :) Could you open a new issue for your black screen? Closing this issue then
