### ISSUE TITLE
Unclear display with black blocks

### ISSUE THREAD

**Issue by niuzehai** [tobspr/RenderPipeline#114]
awesome job!

But I have encountered some problems while running the sample.
![Screenshot from 2019-11-14 17-48-24](https://user-images.githubusercontent.com/22386977/68846210-ab665f80-0707-11ea-931c-f815fb68306a.png)

This is the output information:
[>] CORE                      Using panda3d-supplied core module 
[>] RenderPipeline            Using Python 3.6 with architecture linux_amd64 
[>] RenderPipeline            Using Panda3D 1.11.0 built on Nov 11 2019 03:58:03 
[>] RenderPipeline            Using git commit d08219584d7e16e739a22703543a5f3c361906e7 
[>] MountManager              Auto-Detected base path to /home/ubuntu/3d/RenderPipeline 
[>] RenderPipeline            Mount manager was not mounted, mounting now ... 
[>] MountManager              Setting up virtual filesystem 
[>] MountManager              Mounting auto-detected config dir: /home/ubuntu/3d/RenderPipeline/config/ 
[>] MountManager              Mounting ramdisk as /$$rptemp 
[>] RenderPipeline            No settings loaded, loading from default location 
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
[>] RenderPipeline            Driver Version = 4.3.0 NVIDIA 435.21 
[>] RenderPipeline            Driver Vendor = NVIDIA Corporation 
[>] RenderPipeline            Driver Renderer = TITAN V/PCIe/SSE2 
[>] RenderPipeline            Render resolution is 1600 x 900 
[>] LightManager              Tile size = 24 x 16 , Num tiles = 67 x 57 
[>] GPUCommandQueue           Allocating command buffer of size 32768 
[>] GroupedInputBlock         Native UBO support = False 
[!] RPLoader                  Loading '/$$rp/data/default_cubemap/cubemap.txo' took 206.69 ms
[>] PluginManager             Loading plugin settings 
[>] PluginManager             Creating plugin instances .. 
[>] Debugger                  Creating debugger 
[>] plugin:scattering         Loading scattering method for 'eric_bruneton' 
[>] StageManager              Setup stages .. 
[>] StageManager              Preparing stages .. 
[>] AOStage                   Blur quality is MEDIUM 
[>] UpdatePreviousPipesStage  Creating previous pipes stage .. 
[>] StageManager              Writing shader config 
[>] plugin:pssm               Initializing pssm .. 
[!] RPLoader                  Loading '/$$rp/rpplugins/bloom/resources/lens_dirt.txo' took 80.25 ms
[>] ScatteringMethodEricBruneton Precomputing ... 
[>] RenderPipeline            Finished initialization in 1.397 s, first frame: 3 
[!] RenderPipeline            env_probes plugin is not loaded - cannot add environment probe
[>] RenderPipeline            Took 0.71 s until first frame 
[!] Panda3D                   :linmath(warning): Tried to invert singular LMatrix4.
[>] RenderPipeline            Hiding loading screen after 10 pre-rendered frames. 

Any idea what the issue is?

**Comment by bluekyu** [comment]
This issue may be related to https://github.com/tobspr/RenderPipeline/issues/111#issuecomment-490451592

**Comment by niuzehai** [comment]
> This issue may be related to [#111 (comment)](https://github.com/tobspr/RenderPipeline/issues/111#issuecomment-490451592)

I have already commented on the line in the RenderPipeline/rpcore/shader/render_pipeline_base.inc.glsl

 #ifndef NO_FAST_PRECISION 
 #pragma optionNV (fastprecision on) 
 #endif 

but it still doesn't work.

**Comment by niuzehai** [comment]
I disabled all plugins but still show
![Screenshot from 2019-11-15 13-05-01](https://user-images.githubusercontent.com/22386977/68918333-ab6a6c00-07a8-11ea-92c6-04a4535114fa.png)

**Comment by rdb** [comment]
Closing as the fix has been pushed to master.
