### ISSUE TITLE
Using RenderPipeline in C++?

### ISSUE THREAD

**Issue by Skyliegirl33** [tobspr/RenderPipeline#119]
This project seems very interesting. However, I do find it to be quite a shame that this only works with python. Python doesn't really fit my workflow and I prefer using a "proper" programming language. Would there be any way to use this in C++? I'm not really sure if a lot of work would have to be done to accomplish that.

**Comment by rdb** [comment]
I take issue with your comments about Python not being a "proper" programming language.

**Comment by rdb** [comment]
Oops, hit enter too quickly.  There is a separate project that ported RenderPipeline to C++:
https://github.com/bluekyu/render_pipeline_cpp

Closing it as out-of-scope here.

**Comment by Skyliegirl33** [comment]
I've seen that project, but it's out of date and doesn't work. Thanks anyway, though.

**Comment by tobspr** [comment]
Python is a proper programming language, just to clear that up :)
