### ISSUE TITLE
WIKI Effects page missing

### ISSUE THREAD

**Issue by agoose77** [tobspr/RenderPipeline#21]
Hi Tobspr, 

This is a small non-functional issue, but the wiki page is linked to, yet missing.
Feel free to close this if that's a low priority TODO.

Regards,
Angus

**Comment by tobspr** [comment]
I'm currently working on refactoring the pipeline, but after that I'll add it ! :)

**Comment by tobspr** [comment]
I've started to write the wiki page: https://github.com/tobspr/RenderPipeline/wiki/Effects however its still in progress, and applies to the refactoring_beta branch, not to the master branch.

**Comment by tobspr** [comment]
I just added some updates to the page, it should be complete now, please let me know if it is not.
