### ISSUE TITLE
Theft

### ISSUE THREAD

**Issue by JSandusky** [tobspr/RenderPipeline#23]
You've literally stolen code from a person that has shared so much already.

Karis has shared so much but you find it fit to literally copy and paste his work into your project and call it your own?

This is beyond offensive. You don't even bother to state that by using this the end user is subjected to Epic's license?

**Comment by JSandusky** [comment]
I've already downloaded a complete clone, you can't force push your way out of this one.

**Comment by tobspr** [comment]
I'm not sure what you mean, which part of the code do you think is stolen? If you are correct, I will immediately remove it

**Comment by JSandusky** [comment]
Your BRDFs in the refactoring branch are entirely stolen for a single example. You literally left Karis' comments in place.

**Comment by JSandusky** [comment]
Karis' style is very unique, everyone that has studied PBR knows it well. You cannot pass Karis' code off as your own. Especially since he didn't share that much. You literally copied the exact names of UE4's functions.

**Comment by tobspr** [comment]
IIRC The brdfs where from a Unreal Presentation about introducing Physically Based Shading. Let me check if I can find the presentation again

**Comment by tobspr** [comment]
Until I find it, I'll remove the code, I'm sorry for all the trouble

**Comment by JSandusky** [comment]
There's no trouble, there's just a bloody license confusion

**Comment by tobspr** [comment]
I have removed those files from the repositority, I will remove them from the history soon.

**Comment by JSandusky** [comment]
It's really stupid for those files to be copied, because the BRDFs aren't exactly hard

**Comment by JSandusky** [comment]
Karis did not share the exactness of the fresnel selection for example. Your code literally included the commented out lines of that fresnel selection without bothering to even remove Karis' comments. 

Which is a style that everyone that has even bothered to research the subject will be familiar with.

**Comment by tobspr** [comment]
I'm pretty sure I didn't even mean to commit this file, It probably happened by accident. I'm sorry for that, and I have deleted all references. Is there anything else you want me to do?

**Comment by JSandusky** [comment]
You accidentally committed infringement of copyright? Here I was thinking you avoided any declaration of license regarding the project because you knew you were infringing copyright.

**Comment by JSandusky** [comment]
Do your really believe that the folks in lighting wont notice that you've straight lifted that code too. Everyone that has spent 30 seconds in PBR recognizes Karis' code.

**Comment by tobspr** [comment]
There is a license, right here: https://github.com/tobspr/RenderPipeline/blob/master/LICENSE.txt

**Comment by tobspr** [comment]
I've further investigated into this, and the code i used is both available in an unreal presentation and in a presentation from DICE, see here:
http://www.frostbite.com/wp-content/uploads/2014/11/course_notes_moving_frostbite_to_pbr.pdf

However, I have explicitely stated where the code comes from now, and also added a LICENSE file to the refactoring branch. If you still have concerns, please let me know.

**Comment by JSandusky** [comment]
I think you're good. I am impressed at how quickly you dealt with it.

The actual license Epic's shaders is pretty gray, arguably they're "sample content" but that'd require a formal statement or a precedent in a fight to verify.

I do apologize for the general asshole tone, I could have been more polite.
