### ISSUE TITLE
error in shader?

### ISSUE THREAD

**Issue by subject546** [tobspr/RenderPipeline#25]
hi i have been experimenting with your pipeline.
i recently updated to an newer version of the main branch but got errors about Includes/LightingModels.include missing.
I can't find it anywhere in the repository.

i am using debian jessie x64

the full error code:

$ python2.7 main.py
[-] Main                     Bit System = 64 
[-] Main                     Loading panda3d configuration from configuration.prc .. 
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
[-] Main                     Creating pipeline 
[-] MountManager             Set base path to '.' 
[-] PipelineSettings         Loading ini-file from Config/pipeline.ini 
[-] RenderingPipeline        Setting up render pipeline 
[-] RenderingPipeline        Checking required Panda3D version .. 
[-] MountManager             Setting up virtual filesystem. 
[-] MountManager             Creating temp path, as it does not exist yet 
[-] MountManager             Mounting Temp/ as PipelineTemp/ 
[-] RenderingPipeline        Setting up globals 
[-] GUIManager               Creating GUI .. 
[-] PerformanceOverlay       Init performance overlay .. 
[-] PerformanceOverlay       Starting dummy pstats (text-stats) 
:net(error): Unable to open TCP connection to server 127.0.0.1 on port 5185
:pstats(error): Couldn't connect to PStatServer at localhost:5185
[-] AtmosphericScattering    Precomputing .. 
[-] AtmosphericScattering    Disabled 1  windows while rendering 
[-] AtmosphericScattering    Finished precomputing, also reenabled windows. 
[-] ShaderStructArray        Init array, size = 6 floats= 32 total = 192 
[-] ShadowAtlas              Creating atlas with size 8192 and tile size 256 
[-] ShaderStructArray        Init array, size = 7 floats= 21 total = 147 
[-] ShaderStructArray        Init array, size = 36 floats= 21 total = 756 
[-] LightManager             Batch size = 30 x 17 Actual Buffer size= 1920 x 1088 
[-] IESLoader                Loading IES Profiles from Data/IESProfiles/ 
[!] IESLoader                Only 1 lamp is supported, 2 found: Comet
[!] IESLoader                Only 1 lamp is supported, 8 found: Overhead
[!] IESLoader                Only 1 lamp is supported, 8 found: Round
[!] IESLoader                Only 1 lamp is supported, 2 found: Comet
[!] IESLoader                Only 1 lamp is supported, 8 found: Overhead
[!] IESLoader                Only 1 lamp is supported, 8 found: Round
[-] RenderPassManager        Writing shader autoconfig 
:shader(error): Could not find shader file: Includes/LightingModels.include
included at line 5 of file Includes/Lighting.include:
  #pragma include "Includes/LightingModels.include"
included at line 5 of file Includes/Lights.include:
  #pragma include "Includes/Lighting.include"
included at line 34 of file Shader/UnshadowedLightsPass.fragment:
  #pragma include "Includes/Lights.include"
Traceback (most recent call last):
  File "main.py", line 551, in <module>
    app = Main()
  File "main.py", line 82, in __init__
    self.renderPipeline.create()
  File "/media/subject546/DESERT/libs/RenderPipeline-master/Code/RenderingPipeline.py", line 727, in create
    self.renderPassManager.setShaders()
  File "/media/subject546/DESERT/libs/RenderPipeline-master/Code/RenderPassManager.py", line 158, in setShaders
    generatedShaders += renderPass.setShaders()
  File "/media/subject546/DESERT/libs/RenderPipeline-master/Code/RenderPasses/UnshadowedLightsPass.py", line 57, in setShaders
    self.target.setShader(shader)
  File "/media/subject546/DESERT/libs/RenderPipeline-master/Code/RenderTarget.py", line 166, in setShader
    self.getNode().setShader(shader)
TypeError: NodePath.set_shader() argument 1 must be Shader, not NoneType
[-] PerformanceOverlay       Stopping dummy pstats 
[-] MountManager             Cleaning up .. 

subject546,
btw what markup should i use for errorcode?

**Comment by tobspr** [comment]
Hey, the file was removed for investigation due to somebody claiming it
would have been "stolen code" (which it wasn't, the issue has been
resolved), however I didn't get to recommitting it again, for now you can
just use an older version of the file until I reuploaded it.

I have no clue how to format errors on github tho, I guess pastebin would
work out.

Cheers,
tobspr

**Comment by subject546** [comment]
thx! np for removing it.. (i actually followed that discussion but didn't realize that was this file... :/ ) i think u handled it nicely!
I want to thank u for ur quick response!
