### ISSUE TITLE
Shader input scatteringOptions is not present

### ISSUE THREAD

**Issue by michaeladams** [tobspr/RenderPipeline#26]
Hi,

* Installed panda 1.10 from a nightly build on http://www.panda3d.org/download.php?platform=windows&version=devel&sdk

* Downloaded the RenderPipeline from the master branch

* Created a program based on the sample at https://github.com/tobspr/RenderPipeline/blob/master/Samples/01-Simple/main.py

I ran the sample and received the following issues:

```
  File "F:\dev\Work\tobspr\main.py", line 43, in __init__
    self.skybox = self.renderPipeline.getDefaultSkybox()
AttributeError: RenderingPipeline instance has no attribute 'getDefaultSkybox'
```

So I commented out the skybox code.

```
Traceback (most recent call last):
  File "F:\dev\Work\tobspr\main.py", line 61, in <module>
    app = App()
  File "F:\dev\Work\tobspr\main.py", line 49, in __init__
    self.controller.setInitialPositionHpr(
AttributeError: MovementController instance has no attribute 'setInitialPositionHpr'
```

Commented out the controller code

```
  File "F:\dev\Work\tobspr\main.py", line 61, in <module>
    app = App()
  File "F:\dev\Work\tobspr\main.py", line 58, in __init__
    self.renderPipeline.onSceneInitialized()
AttributeError: RenderingPipeline instance has no attribute 'onSceneInitialized'
```

Commented out the onSceneInitialized...

```
  File "F:\dev\Work\tobspr\main.py", line 62, in <module>
    app.run()
  File "F:\dev\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 2979, in run
    self.taskMgr.run()
  File "F:\dev\Panda3D-1.10.0\direct\task\Task.py", line 508, in run
    self.step()
  File "F:\dev\Panda3D-1.10.0\direct\task\Task.py", line 465, in step
    self.mgr.poll()
  File "F:\dev\Panda3D-1.10.0\direct\showbase\ShowBase.py", line 1886, in __igLoop
    self.graphicsEngine.renderFrame()
AssertionError: Shader input scatteringOptions.transmittanceNonLinear is not present.
 at line 412 of c:\buildslave\sdk-windows-amd64\build\panda\src\pgraph\shaderAttrib.cxx
```

And - I couldn't get past this issue.  I initially tried setting up the render pipeline in my existing project, and got the same issue, but I thought it might be because I'm using some custom shaders.  So I setup a clean project, and get the same problem.  Any ideas?  Do I need to throw render some default shader inputs?

**Comment by tobspr** [comment]
Hi, this is a strange issue, usually you should not have to comment out anything, the errors you get are because you commented out those lines.
I will investigate into this this afternoon, I believe the sample might be outdated.

Cheers,
tobspr

**Comment by tobspr** [comment]
Hm, can you make sure you checked out the master and not the refactoring_beta branch? In the master branch the functions are named different, so thats what could cause your issue

**Comment by michaeladams** [comment]
Gah - sometimes I'm such as idiot.  I'm not sure what happened there, but yeah - I didn't grab the correct version.  After replacing the lightingModels.include, I'm now running the sample.

I did have to disable GI - as it kept displaying the 'computing gi - be patient', and wouldn't continue.  But I'm mainly looking to use the awesome lighting / shadowing - so thats not an issue for me.

Thanks for the help anyway!
