### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by alabd14313** [tobspr/RenderPipeline#38]
Hi!
I have a question. Where is demos?
and I have a feature request:
1 - Volumetric Fog
2- Area lights
3- Particle system (light sensitive and collision-detection)
Thx

**Comment by tobspr** [comment]
Hi, you can find the demos here: https://github.com/tobspr/RenderPipeline-Samples (although the setup also asks to download them)

1. Volumetric fog is already in in the latest version - the plugin is named volumetrics
2. Basic support for spherical area lights is in, but not enabled yet - Area lights are definitely planned and on my todo list (Rectangle, Sphere and Tube area lights)
3. Panda3D already has particle systems, although I'm planning to implement GPU based particle systems for the pipeline - also on my todo list :) This requires proper alpha blending first though.

**Comment by alabd14313** [comment]
Here is Martins upitis area light setup in blender. I hope it help you:


[area_lights_cornellbox_1.blend.zip](https://github.com/tobspr/RenderPipeline/files/192269/area_lights_cornellbox_1.blend.zip)

**Comment by tobspr** [comment]
Oh well thats nice! Will certainly help me out :)

**Comment by alabd14313** [comment]
Do you want more shaders in blender?

**Comment by tobspr** [comment]
What kind of shaders did you think of?

**Comment by alabd14313** [comment]
GLSL

**Comment by tobspr** [comment]
Well I was more thinking about the type of shaders, i.e. lighting, effects, etc :)

**Comment by alabd14313** [comment]
Here you are. but I thanks from blender users:
[underWaterDistortionFilter.blend.zip](https://github.com/tobspr/RenderPipeline/files/192289/underWaterDistortionFilter.blend.zip)
[river.blend.zip](https://github.com/tobspr/RenderPipeline/files/192291/river.blend.zip)
[flameFilter.blend.zip](https://github.com/tobspr/RenderPipeline/files/192292/flameFilter.blend.zip)
Do you want more, Somethings like Cell shading, old film, water, material shaders and so on?

**Comment by alabd14313** [comment]
Seasons light and weather:
[Demo_video](http://www.aparat.com/v/5hI8Z/%D9%82%D9%88%DB%8C_%D8%AA%D8%B1%DB%8C%D9%86_%D9%85%D9%88%D8%AA%D9%88%D8%B1_%D8%A8%D8%A7%D8%B2%DB%8C_%D8%B3%D8%A7%D8%B2%DB%8C_snow_drop_%D8%B4%D8%B1%DA%A9%D8%AA_ubisoft)

**Comment by tobspr** [comment]
Ah thanks - well for most things I already have a plan on how to implement them - Are there any particular effects (besides of the ones you mentioned) you are interested in getting them into the pipeline?

**Comment by alabd14313** [comment]
I think about panda3d hive system and blender as an editor for panda (material and glsl). What do you think?

**Comment by alabd14313** [comment]
One thing that confused me is a hardware independent gpu programmgin. Cuda is a constraint, whether openCL haven't a fixed implementation. I research more to find a solution.

**Comment by alabd14313** [comment]
[area-lighting-casting-point.zip](https://github.com/tobspr/RenderPipeline/files/192338/area-lighting-casting-point.zip)

**Comment by alabd14313** [comment]
I will find a solution for geometry and compute shaders...

**Comment by tobspr** [comment]
The render pipeline uses GLSL shaders, so its fine, thanks for the resources :)

**Comment by tobspr** [comment]
FYI, spherical area lights are supported now. I will implement rectangle and tube area lights as soon as I find time for it.

**Comment by alabd14313** [comment]
Thank you very much!
Good luck...

**Comment by alabd14313** [comment]
Blender Candy branch, textured area lights:
[Video](https://www.youtube.com/watch?v=3JUYFGkmE1Y)
