### ISSUE TITLE
Setup not running correctly.

### ISSUE THREAD

**Issue by moonshineTheleocat** [tobspr/RenderPipeline#44]
Hey, the set up does not seem to run correctly with windows 10. So... just a quick note, because it's borderline impossible to find VS 2010, I have two different VS installed on my system. 2013, 2015. To build panda, I had to swap the projects to Windows SDK 7.1 and it was built with Eigen.

I ran across a rather frustrating part in the setup process.

This is a copy and paste from the setup when I tried to build the C++ modules. My first thought was to simply go into the python script and make the change. However it appears that Cmake 3.x does not see Windows SDK 7.1

http://pastebin.com/yZayy77d

So I tried to just roll with the python scripts... annnnd this shows up.

http://pastebin.com/ePcLRHXv

I'm not even sure what to do with this one. I see two errors that's caused by some sort of finnickyness with GLSL's compiler. Then that bottom was is the kicker... the file doesn't even go past 2000 lines.

**Comment by tobspr** [comment]
To use a different version of visual studio, you have to go to `rpcore/native/config.ini` and set the appropriate visual studio version, e.g. `vc_version=Visual Studio 13 2013` I think (If you use `cmake --help` you can see a list of detected compilers). This should fix the first issue - if it doesn't, please let me know so I can fix it.

For the second issue, I just committed a fix, let me know if it works (I wasn't able to test it yet).

**Comment by moonshineTheleocat** [comment]
Fantastic! So that fixed the problem of compiling. It both the shaders, and the C++ natives (Visual Studio 12 2013 by the way.)

However, I seem to have run into another problem. It looks like that attempting to run the samples are not successful. I've ran only a few, but the patterns are common enough to show me that it seems to happen at the same point.

**Comment by tobspr** [comment]
Hm its hard to tell, I would need some more information - Can you hit the "Debug" button after the program crashed (the one in your second screenshot) and attach a screenshot what it shows then (You will have to select Visual Studio as a debugger). 

(I should probably also remove the warnings about slow loading of assets - It seems your disk seems to be a bit slower, causing each resource to load slowly and thus spam those warnings)

**Comment by moonshineTheleocat** [comment]
Welp, now I feel self concious about my hard disk. Then again, the WD Black I had before it went to crap, and the one I got back looked a bit dinged up.

Oh well. I was planning on a new hard drive anyways. Any recommendations?

Anyways. I'll go ahead and try it when I get back. It -could- be a possibility that it's the compilation difference between the two. Given that Panda was compiled using Visual Studios, but the compiler was from the Windows 7.1 SDK. CMAKE apparently doesn't see it, yet it says I have the Visual Studios 10 builder on the platform. 

Push comes to shove, I might need to do some changes to VS to change the default compiler.

**Comment by moonshineTheleocat** [comment]
It looks like it does have to do something with the way the C++ modules are compiled.

Pressing debug however does not provide the most helpful information.

**Comment by moonshineTheleocat** [comment]
I managed to find a copy of visual studios 2010 online, I'm going to try that when I download it. I seriously wander why people have not upgraded to a more recent visual studios =-=, it seems that it's either 2010 or 2012 which are incredibly hard to find now, or no longer supported.

**Comment by rdb** [comment]
The reason why Panda3D is still compiled with MSVC 2010 is because it's the last compiler to still support Windows XP, which still makes up a non-negligible portion of Panda3D's user base.

**Comment by moonshineTheleocat** [comment]
Alright I got it working.

Definitely the easiest way was to download Visual Studios 2010 then to fool with everything else.

**Comment by tobspr** [comment]
Hm, well yeah I guess the issue was that something was different in your Panda3D build than the render pipeline native build.

About the the flickering  - I will have a look at it when I come home, maybe the GLSL warnings you get are related.

**Comment by tobspr** [comment]
@moonshineTheleocat which drivers are you using btw? It seems your driver is a bit weird, do you have a chance to try a newer version? Also which GPU do you use?

**Comment by moonshineTheleocat** [comment]
AMD HD7950

Driver Packaging Version
 16.15.2211

OpenGL® Version
6.14.10.13431

**Comment by tobspr** [comment]
I just committed a fix for your GLSL warnings - let me know if it works for you, maybe the other issues you were getting are related.

If you have any suggestions/improvements then feel free to open another issue :) Same goes for questions - they are not really issues, but that should be fine, this way others can also see the answers.
