### ISSUE TITLE
Path update in wiki (code -> rpcore)

### ISSUE THREAD

**Issue by germn** [tobspr/RenderPipeline#47]
https://github.com/tobspr/RenderPipeline/wiki/Building-the-CPP-Modules

> `code/native/`

To:

> `rpcore/native/`

**Comment by tobspr** [comment]
Thanks, fixed it!

**Comment by germn** [comment]
Sory for being inaccurate: there're two more places, where path should be updated:

> If you're clever enough, check **Code/Native/**Scripts/setup.py to see how it constructs the cmake command line.

> Also, the entire <arch> directory under **code/native/** is auto-generated; if you get stuck somewhere, you can delete it to start fresh.

**Comment by tobspr** [comment]
Ah, thanks, I missed that!
