### ISSUE TITLE
Error in `#pragma include` while setup.py

### ISSUE THREAD

**Issue by germn** [tobspr/RenderPipeline#48]
I'm getting this error while setup.py:

> [ 05 ]  Precomputing film grain ..
>         Running script: data/film_grain/generate.py
> :display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader grain.compute.glsl:
> ERROR: grain.compute.glsl:10: '' :  illegal character (") (0x22)
> ERROR: grain.compute.glsl:10: '' :  #pragma directive must end with a newline
> 
> :display:gsg:glgsg(error): An error occurred while linking GLSL shader
> Link called without any attached shader objects.

Windows 10
Intel HD 4600 (latest drivers)

Is `#pragma include` part of GLSL (I couldn't find info about this directive) or it processed somewhere else?

**Comment by tobspr** [comment]
Ah, seems your compiler tries to parse the pragma. It is preprocessed by Panda3D, but the original #pragma statement is kept in the shader source. 

Feel free to report an issue to the Panda3D repository, since this is a panda related issue.

**Comment by germn** [comment]
Thanks, reported:
https://bugs.launchpad.net/panda3d/+bug/1568884

**Comment by rdb** [comment]
Fix has been committed to latest Panda. https://github.com/panda3d/panda3d/commit/873fd3294a91589525ad5be408577be754258ff2

**Comment by tobspr** [comment]
Thanks!
