### ISSUE TITLE
 how to screen the volumetric clouds ?

### ISSUE THREAD

**Issue by sazearte** [tobspr/RenderPipeline#55]
I load last version of render pipeline and Terrain sample, but i have not volumetric clouds, How to activate ?

**Comment by tobspr** [comment]
You have to enable the volumetric clouds plugin, either using the plugin
configurator or by manually enabling it in config/pipeline.yaml
Am 10.06.2016 10:58 schrieb "sazearte" <notifications@github.com>:

**Comment by sazearte** [comment]
ok thanks
