### ISSUE TITLE
TCP connection failed and changing the ground effect

### ISSUE THREAD

**Issue by Hagar27** [tobspr/RenderPipeline#56]
I have an error which arises randomly while running my game using the render pipeline which cause the game to stop for few seconds and runs again while the error appears on the screen 
Here's the error Link http://pastebin.com/eyxJRe0i

Also another thing , the ground texture has some effects that i don't want , it seems like there's water on the ground , how can I change this ?

**Comment by tobspr** [comment]
Maybe you are accidentally pressing the "1" key? Because then the render pipeline tries to connect to pstats, and if pstats is not running, it will cause the application to freeze until the request times out.

What material does your ground have? Which roughness and Index of refraction did you set?

**Comment by Hagar27** [comment]
Actually I thought this was the issue but I intentionally pressed "1" key and nothing happened.

the ground seems to have water on it and I set the ground material in blender before importing it to panda (diffuse intensity .8 / specular intensity 0 / hardness 50 / shiness 12,5 / index of refraction 1.5 / roughness .3)

**Comment by Hagar27** [comment]
Also I always have this warning while running the pipeline http://pastebin.com/wEDPpdCL

**Comment by tobspr** [comment]
You need to export your model using the BAM exporter, and you also have to use the Properties which in the Physically Based Shading panel (Which the BAM exporter provides)

**Comment by Hagar27** [comment]
I did export the model using bam exporter and I use the Physically Based Shading panel to change the properties but still looks like there's water on the ground

**Comment by tobspr** [comment]
Which roughness parameters did you choose? Did you export to the .BAM format?

**Comment by Hagar27** [comment]
0.5
