### ISSUE TITLE
Shader compilation fails with "error(#206) Assigning non-constant to: const highp float"

### ISSUE THREAD

**Issue by jakogut** [tobspr/RenderPipeline#58]
I tried running some of the samples from Render Pipeline on Linux, with the 4.7-rc6 kernel amdgpu driver, and the 16.30.3.306809 release of amdgpu-pro in userspace. The driver supports OpenGL 4.5.

There are shader compilation errors, and Panda3D reports "no code generated" for the failing shaders. The graphical output is black.

I traced the problem to shaders which declare certain floats as const. I removed the const qualifiers from a few of the problematic shaders, and got 01-Material-Demo to run. (It looks and performs amazingly, fantastic work!)

Is this something that's vendor/driver specific? I seem to remember having a similar problem a little while back with the pipline on Intel HD Graphics on Windows. If removing the const qualifier in these shaders won't break compatibility with any other vendors or drivers, I'll make a pull request for it.

**Comment by jakogut** [comment]
It seems most (if not all) the samples run fine, just by removing the const qualifier from two motion blur shaders. Here's a patch:

https://gist.github.com/jakogut/ce38532497d44c3095d2aba9bf9e162f

**Comment by tobspr** [comment]
Hi, sorry, I didn't see your issue. Could you make a pull request so I can merge it? :)
