### ISSUE TITLE
problem with 2015 c++ compiler

### ISSUE THREAD

**Issue by huitre39** [tobspr/RenderPipeline#62]
Hello, If i try to compile with C++ 2015 compiler i have 6 errors

**Comment by tobspr** [comment]
Could you please attach the errors you are getting?

**Comment by huitre39** [comment]
Yes, but terminal not indent, it's not very easy to read :

`[ 03 ]  Building the native code .. (This might take a while!)
        Running script: rpcore/native/build.py


[!] FATAL ERROR: b'Subprocess returned no-zero statuscode!'
Failed to execute 'build.py'
Output: Command '['C:\\Panda3D-1.10.0-3.5-x64\\python\\python.exe', '-B', 'build.py', '--clean']' returned non-zero exit status 1
 Cleaning up output directory ..
b'Creating directory' b'C:\\RenderPipeline-master\\rpcore\\native\\scripts\\..\\win_amd64_py35'
b'Executing command: ' b'cmake C:/RenderPipeline-master/rpcore/native -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_EXECUTABLE:STRING=C:\\Panda3D-1.10.0-3.5-x64\\python\\python.exe -DPROJECT_NAME:STRING=native_ -DINTERROGATE_LIB:STRING=libp3interrogatedb -GVisual Studio 14 2015 Win64 -DPYTHONVER:STRING=35 -DUSE_LIB_EIGEN=TRUE -DIGATE_VERBOSE=0 -DOPTIMIZE=3' b'\n'
b'Process output: '
b'-- The C compiler identification is MSVC 19.0.23506.0\r\n-- The CXX compiler identification is MSVC 19.0.23506.0\r\n-- Check for working C compiler: D:/VS2015/VC/bin/x86_amd64/cl.exe\r\n-- Check for working C compiler: D:/VS2015/VC/bin/x86_amd64/cl.exe -- works\r\n-- Detecting C compiler ABI info\r\n-- Detecting C compiler ABI info - done\r\n-- Check for working CXX compiler: D:/VS2015/VC/bin/x86_amd64/cl.exe\r\n-- Check for working CXX compiler: D:/VS2015/VC/bin/x86_amd64/cl.exe -- works\r\n-- Detecting CXX compiler ABI info\r\n-- Detecting CXX compiler ABI info - done\r\n-- Detecting CXX compile features\r\n-- Detecting CXX compile features - done\r\n-- Configuring done\r\n-- Generating done\r\n-- Build files have been written to: C:/RenderPipeline-master/rpcore/native/win_amd64_py35\r\n'
b'Executing command: ' b'cmake --build . --config RelWithDebInfo -- /m' b'\n'
b'Process error:'
b'Microsoft (R) Build Engine, version 14.0.24720.0\r\nCopyright (C) Microsoft Corporation. Tous droits rservs.\r\n\r\nLa gnration a dmarr 10/09/2016 17:26:20.\r\nLa cible "BeforeGenerateProjectPriFile" rpertorie dans un attribut BeforeTargets  "C:\\Program Files (x86)\\MSBuild\\Microsoft\\NuGet\\Microsoft.NuGet.targets (186,61)" n\'existe pas dans le projet et sera ignore.\r\nLa cible "BeforeGenerateProjectPriFile" rpertorie dans un attribut BeforeTargets  "C:\\Program Files (x86)\\MSBuild\\Microsoft\\NuGet\\Microsoft.NuGet.targets (186,61)" n\'existe pas dans le projet et sera ignore.\r\nLa cible "BeforeGenerateProjectPriFile" rpertorie dans un attribut BeforeTargets  "C:\\Program Files (x86)\\MSBuild\\Microsoft\\NuGet\\Microsoft.NuGet.targets (186,61)" n\'existe pas dans le projet et sera ignore.\r\n     1>Projet "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\ALL_BUILD.vcxproj" sur le noud 1 (cibles par dfaut).\r\n     1>Le projet "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\ALL_BUILD.vcxproj" (1) gnre "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\ZERO_CHECK.vcxproj" (2) sur le noud 1 (cibles par dfaut).\r\n     2>PrepareForBuild:\r\n         Cration du rpertoire "x64\\RelWithDebInfo\\ZERO_CHECK\\".\r\n         Cration du rpertoire "x64\\RelWithDebInfo\\ZERO_CHECK\\ZERO_CHECK.tlog\\".\r\n       InitializeBuildStatus:\r\n         Cration de "x64\\RelWithDebInfo\\ZERO_CHECK\\ZERO_CHECK.tlog\\unsuccessfulbuild", car "AlwaysCreate" a t spcifi.\r\n       CustomBuild:\r\n         Checking Build System\r\n         CMake does not need to re-run because C:/RenderPipeline-master/rpcore/native/win_amd64_py35/CMakeFiles/generate.stamp is up-to-date.\r\n       FinalizeBuildStatus:\r\n         Suppression du fichier "x64\\RelWithDebInfo\\ZERO_CHECK\\ZERO_CHECK.tlog\\unsuccessfulbuild".\r\n         Mise  jour de l\'horodatage "x64\\RelWithDebInfo\\ZERO_CHECK\\ZERO_CHECK.tlog\\ZERO_CHECK.lastbuildstate".\r\n     2>Gnration du projet "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\ZERO_CHECK.vcxproj" termine (cibles par dfaut).\r\n     1>Le projet "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\ALL_BUILD.vcxproj" (1) gnre "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj" (3) sur le noud 2 (cibles par dfaut).\r\n     3>PrepareForBuild:\r\n         Cration du rpertoire "native_.dir\\RelWithDebInfo\\".\r\n         Cration du rpertoire "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\RelWithDebInfo\\".\r\n         Cration du rpertoire "native_.dir\\RelWithDebInfo\\native_.tlog\\".\r\n       InitializeBuildStatus:\r\n         Cration de "native_.dir\\RelWithDebInfo\\native_.tlog\\unsuccessfulbuild", car "AlwaysCreate" a t spcifi.\r\n       CustomBuild:\r\n         Building Custom Rule C:/RenderPipeline-master/rpcore/native/CMakeLists.txt\r\n         CMake does not need to re-run because C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\CMakeFiles\\generate.stamp is up-to-date.\r\n       ClCompile:\r\n         D:\\VS2015\\VC\\bin\\x86_amd64\\CL.exe /c /I"C:\\Panda3D-1.10.0-3.5-x64\\thirdparty\\win-libs-vc10-x64\\eigen\\include" /I"C:\\Panda3D-1.10.0-3.5-x64\\include" /I"C:\\Panda3D-1.10.0-3.5-x64\\python\\include" /I"C:\\RenderPipeline-master\\rpcore\\native\\source" /Zi /nologo /W3 /WX- /MP /O2 /Ob2 /Oi /Ot /D WIN32 /D _WINDOWS /D WIN64_VC /D WIN64 /D WIN32_VC /D WIN32 /D EIGEN_MPL2_ONLY= /D EIGEN_NO_DEBUG= /D EIGEN_NO_STATIC_ASSERT= /D _HAS_EXCEPTIONS=0 /D PB_MODULE=native_ /D PB_CFG_MODULE=native_ /D "CMAKE_INTDIR=\\"RelWithDebInfo\\"" /D native__EXPORTS /D _WINDLL /D _MBCS /Gm- /EHsc /MD /GS- /fp:fast /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /Fo"native_.dir\\RelWithDebInfo\\\\" /Fd"native_.dir\\RelWithDebInfo\\vc140.pdb" /Gd /TP /wd4996 /wd4275 /wd4267 /wd4101 /wd4273 /errorReport:queue  /favor:blend /bigobj /Zm300 /GM- "C:\\RenderPipeline-master\\rpcore\\native\\source\\config_rsnative.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\gpu_command.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\gpu_command_list.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\ies_dataset.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\internal_light_manager.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\interrogate_module.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\interrogate_wrapper.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\pssm_camera_rig.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\pssm_helper.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\rp_light.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\rp_point_light.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\rp_spot_light.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\shadow_atlas.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\shadow_manager.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\shadow_source.cpp" "C:\\RenderPipeline-master\\rpcore\\native\\source\\tag_state_manager.cpp"\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         config_rsnative.cpp\r\n         gpu_command.cpp\r\n         gpu_command_list.cpp\r\n     3>cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         ies_dataset.cpp\r\n         internal_light_manager.cpp\r\n         interrogate_module.cpp\r\n         interrogate_wrapper.cpp\r\n         pssm_camera_rig.cpp\r\n         pssm_helper.cpp\r\n         rp_light.cpp\r\n         rp_point_light.cpp\r\n         rp_spot_light.cpp\r\n         shadow_atlas.cpp\r\n         shadow_manager.cpp\r\n         shadow_source.cpp\r\n         tag_state_manager.cpp\r\n       Link:\r\n         D:\\VS2015\\VC\\bin\\x86_amd64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\RelWithDebInfo\\native_.dll" /INCREMENTAL /NOLOGO /LIBPATH:"C:/Panda3D-1.10.0-3.5-x64/lib" /LIBPATH:"C:/Panda3D-1.10.0-3.5-x64/lib/RelWithDebInfo" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\\Panda3D-1.10.0-3.5-x64\\python\\libs\\python35.lib" libp3framework.lib libpanda.lib libpandaexpress.lib libp3dtool.lib libp3dtoolconfig.lib libp3direct.lib libp3interrogatedb.lib /MANIFEST /MANIFESTUAC:"level=\'asInvoker\' uiAccess=\'false\'" /manifest:embed /DEBUG /PDB:"C:/RenderPipeline-master/rpcore/native/win_amd64_py35/RelWithDebInfo/native_.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/RenderPipeline-master/rpcore/native/win_amd64_py35/RelWithDebInfo/native_.lib" /MACHINE:X64  /machine:x64 /DLL native_.dir\\RelWithDebInfo\\config_rsnative.obj\r\n         native_.dir\\RelWithDebInfo\\gpu_command.obj\r\n         native_.dir\\RelWithDebInfo\\gpu_command_list.obj\r\n         native_.dir\\RelWithDebInfo\\ies_dataset.obj\r\n         native_.dir\\RelWithDebInfo\\internal_light_manager.obj\r\n         native_.dir\\RelWithDebInfo\\interrogate_module.obj\r\n         native_.dir\\RelWithDebInfo\\interrogate_wrapper.obj\r\n         native_.dir\\RelWithDebInfo\\pssm_camera_rig.obj\r\n         native_.dir\\RelWithDebInfo\\pssm_helper.obj\r\n         native_.dir\\RelWithDebInfo\\rp_light.obj\r\n         native_.dir\\RelWithDebInfo\\rp_point_light.obj\r\n         native_.dir\\RelWithDebInfo\\rp_spot_light.obj\r\n         native_.dir\\RelWithDebInfo\\shadow_atlas.obj\r\n         native_.dir\\RelWithDebInfo\\shadow_manager.obj\r\n         native_.dir\\RelWithDebInfo\\shadow_source.obj\r\n         native_.dir\\RelWithDebInfo\\tag_state_manager.obj\r\n            Cration de la bibliothque C:/RenderPipeline-master/rpcore/native/win_amd64_py35/RelWithDebInfo/native_.lib et de l\'objet C:/RenderPipeline-master/rpcore/native/win_amd64_py35/RelWithDebInfo/native_.exp\r\n     3>pssm_camera_rig.obj : error LNK2019: symbole externe non rsolu "__declspec(dllimport) public: __cdecl LVecBase2f::LVecBase2f(class LVecBase2f &&)" (__imp_??0LVecBase2f@@QEAA@$$QEAV0@@Z) rfrenc dans la fonction "protected: class LVecBase2f * __cdecl std::vector<class LVecBase2f,class std::allocator<class LVecBase2f> >::_Umove<class LVecBase2f *>(class LVecBase2f *,class LVecBase2f *,class LVecBase2f *)" (??$_Umove@PEAVLVecBase2f@@@?$vector@VLVecBase2f@@V?$allocator@VLVecBase2f@@@std@@@std@@IEAAPEAVLVecBase2f@@PEAV2@00@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>pssm_camera_rig.obj : error LNK2019: symbole externe non rsolu "__declspec(dllimport) public: class LVecBase2f & __cdecl LVecBase2f::operator=(class LVecBase2f &&)" (__imp_??4LVecBase2f@@QEAAAEAV0@$$QEAV0@@Z) rfrenc dans la fonction "protected: void __cdecl PSSMCameraRig::compute_pssm_splits(class LMatrix4f const &,float,class LVecBase3f const &)" (?compute_pssm_splits@PSSMCameraRig@@IEAAXAEBVLMatrix4f@@MAEBVLVecBase3f@@@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>pssm_camera_rig.obj : error LNK2019: symbole externe non rsolu "__declspec(dllimport) public: class LVecBase3f & __cdecl LVecBase3f::operator=(class LVecBase3f &&)" (__imp_??4LVecBase3f@@QEAAAEAV0@$$QEAV0@@Z) rfrenc dans la fonction "protected: void __cdecl PSSMCameraRig::compute_pssm_splits(class LMatrix4f const &,float,class LVecBase3f const &)" (?compute_pssm_splits@PSSMCameraRig@@IEAAXAEBVLMatrix4f@@MAEBVLVecBase3f@@@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>rp_point_light.obj : error LNK2019: symbole externe non rsolu "__declspec(dllimport) public: class BoundingSphere & __cdecl BoundingSphere::operator=(class BoundingSphere &&)" (__imp_??4BoundingSphere@@QEAAAEAV0@$$QEAV0@@Z) rfrenc dans la fonction "public: void __cdecl ShadowSource::set_perspective_lens(float,float,float,class LVecBase3f,class LVecBase3f)" (?set_perspective_lens@ShadowSource@@QEAAXMMMVLVecBase3f@@0@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>rp_spot_light.obj : error LNK2001: symbole externe non rsolu "__declspec(dllimport) public: class BoundingSphere & __cdecl BoundingSphere::operator=(class BoundingSphere &&)" (__imp_??4BoundingSphere@@QEAAAEAV0@$$QEAV0@@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\RelWithDebInfo\\native_.dll : fatal error LNK1120: 4 externes non rsolus [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n     3>Gnration du projet "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj" termine (cibles par dfaut) -- CHEC.\r\n     1>Gnration du projet "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\ALL_BUILD.vcxproj" termine (cibles par dfaut) -- CHEC.\r\n\r\nCHEC de la build.\r\n\r\n       "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\ALL_BUILD.vcxproj" (cible par dfaut) (1) ->\r\n       "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj" (cible par dfaut) (3) ->\r\n       (ClCompile cible) -> \r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/GM\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         cl : Ligne de commande warning D9002: option \'/G-\' inconnue ignore [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n\r\n\r\n       "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\ALL_BUILD.vcxproj" (cible par dfaut) (1) ->\r\n       "C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj" (cible par dfaut) (3) ->\r\n       (Link cible) -> \r\n         pssm_camera_rig.obj : error LNK2019: symbole externe non rsolu "__declspec(dllimport) public: __cdecl LVecBase2f::LVecBase2f(class LVecBase2f &&)" (__imp_??0LVecBase2f@@QEAA@$$QEAV0@@Z) rfrenc dans la fonction "protected: class LVecBase2f * __cdecl std::vector<class LVecBase2f,class std::allocator<class LVecBase2f> >::_Umove<class LVecBase2f *>(class LVecBase2f *,class LVecBase2f *,class LVecBase2f *)" (??$_Umove@PEAVLVecBase2f@@@?$vector@VLVecBase2f@@V?$allocator@VLVecBase2f@@@std@@@std@@IEAAPEAVLVecBase2f@@PEAV2@00@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         pssm_camera_rig.obj : error LNK2019: symbole externe non rsolu "__declspec(dllimport) public: class LVecBase2f & __cdecl LVecBase2f::operator=(class LVecBase2f &&)" (__imp_??4LVecBase2f@@QEAAAEAV0@$$QEAV0@@Z) rfrenc dans la fonction "protected: void __cdecl PSSMCameraRig::compute_pssm_splits(class LMatrix4f const &,float,class LVecBase3f const &)" (?compute_pssm_splits@PSSMCameraRig@@IEAAXAEBVLMatrix4f@@MAEBVLVecBase3f@@@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         pssm_camera_rig.obj : error LNK2019: symbole externe non rsolu "__declspec(dllimport) public: class LVecBase3f & __cdecl LVecBase3f::operator=(class LVecBase3f &&)" (__imp_??4LVecBase3f@@QEAAAEAV0@$$QEAV0@@Z) rfrenc dans la fonction "protected: void __cdecl PSSMCameraRig::compute_pssm_splits(class LMatrix4f const &,float,class LVecBase3f const &)" (?compute_pssm_splits@PSSMCameraRig@@IEAAXAEBVLMatrix4f@@MAEBVLVecBase3f@@@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         rp_point_light.obj : error LNK2019: symbole externe non rsolu "__declspec(dllimport) public: class BoundingSphere & __cdecl BoundingSphere::operator=(class BoundingSphere &&)" (__imp_??4BoundingSphere@@QEAAAEAV0@$$QEAV0@@Z) rfrenc dans la fonction "public: void __cdecl ShadowSource::set_perspective_lens(float,float,float,class LVecBase3f,class LVecBase3f)" (?set_perspective_lens@ShadowSource@@QEAAXMMMVLVecBase3f@@0@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         rp_spot_light.obj : error LNK2001: symbole externe non rsolu "__declspec(dllimport) public: class BoundingSphere & __cdecl BoundingSphere::operator=(class BoundingSphere &&)" (__imp_??4BoundingSphere@@QEAAAEAV0@$$QEAV0@@Z) [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n         C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\RelWithDebInfo\\native_.dll : fatal error LNK1120: 4 externes non rsolus [C:\\RenderPipeline-master\\rpcore\\native\\win_amd64_py35\\native_.vcxproj]\r\n\r\n    18 Avertissement(s)\r\n    6 Erreur(s)\r\n\r\nTemps coul 00:00:52.12\r\n'


Setup failed:    Python script didn't return properly!

Please fix the above errors and then restart the setup.`

**Comment by sazearte** [comment]
I tested, i have same problems

**Comment by huitre39** [comment]
i create new virtual machine with Windows10 64bits anniversary and VS2015 64bits and last beta release of Panda3d.

I have same errors.

**Comment by rdb** [comment]
If you want to use MSVC 2015, you have to use a build of Panda3D that is compiled with MSVC 2015.  Otherwise, it is recommended that you use Windows 7 SDK (2010) instead.

**Comment by huitre39** [comment]
yes but i can not use 2010 with python 3 ?

**Comment by rdb** [comment]
Yes, you can.  The Panda3D buildbot builds for Python 3.5 are still compiled with MSVC 2010.

If you want to use MSVC 2015, one way is to compile Panda3D for MSVC 2015.  This is still experimental, however.  More information here:
https://www.panda3d.org/forums/viewtopic.php?f=9&t=18775

**Comment by huitre39** [comment]
i tested and it's works.

I also tested the samples
It all work except "08- Terrain"
i have exeption :
`Exception: Attempt to spawn multiple ShowBase instances!`
