### ISSUE TITLE
Poor Performance

### ISSUE THREAD

**Issue by RodrigoMedeirosrRS** [tobspr/RenderPipeline#63]
Hellor friend, i am trying some samples with my PC, and i have a performance problens. In all the samples the FPS rate is ever around 10fps. I try to reduce the resolution, but the problem persist.

My PC configs:
- Core i7 3612QM
- 8GB Ram
- GPU Nvidia 630m

I belive the problem is into the Optimus GPU, so any ideia hou i can solve it?

**Comment by tobspr** [comment]
Hi,

The 630m is a pretty low end card, and the Render Pipeline is mostly
targeted to mid/high end hardware.
You can disable some plugins to get better performance, but of course it
won't look good.

Best regards,
tobspr
