### ISSUE TITLE
Editor Won't open

### ISSUE THREAD

**Issue by RodrigoMedeirosrRS** [tobspr/RenderPipeline#65]
Hello!

I have updated the RP yesterday, and i found the material editor into the Toolkit folder. But, when i try to open it, i found this error:

![material editor - error](https://cloud.githubusercontent.com/assets/7956669/20569310/c5a460ec-b186-11e6-96b3-e27e324f6300.png)

I already install the PyQT5, and the other tools are working normally. I need install another dependency to use it, or its bug?

**Comment by tobspr** [comment]
Thats a weird error, because the file should exist. Do you, by any chance, have a module named `ui` in your python environment? You can check so by executing `python -m ui`.

**Comment by RodrigoMedeirosrRS** [comment]
I am using a Python 2.7, and you are correct, i don't have ui module on my python. How exactly python ui module i need install?

**Comment by tobspr** [comment]
No, its fine if you don't have an ui module, since the ui "module" is in the material editor folder. Do the plugin configurator / time of day editor work for you?

**Comment by RodrigoMedeirosrRS** [comment]
Yes, both the Time of Day and Plugin Configurator is working so fine.

**Comment by tobspr** [comment]
Can you check if `ui/main_window_generated.py` exists in the material editor folder?

**Comment by tobspr** [comment]
FYI, you can make it work by adding an empty `__init__.py` in the `material_editor/gui` folder. Seems Python 2 / 3 behave different in this case. I will add it to the repository when I merge the experimental branch.
