### ISSUE TITLE
Can't Build RP on Windows

### ISSUE THREAD

**Issue by RodrigoMedeirosrRS** [tobspr/RenderPipeline#71]
Hello friend.

I am trying to build RP on my new PC, on Linux everthing works fine, but on windows is occour a strange error:
`Running script: rpcore/native/build.py
Traceback (most recent call last):
  File "build.py", line 52, in <module>
    run_cmake_build(config, args)
  File "C:\Render\rpcore\native\scripts\setup.py", line 156, in run_cmake_build
    try_execute("cmake", "--build", ".", "--config", configuration, "--", core_option)
  File "C:\Render\rpcore\native\scripts\common.py", line 216, in try_execute
    raise Exception("Process had non-zero returncode:", process.returncode)
Exception: ('Process had non-zero returncode:', 1)
Failed to execute 'build.py'
Output: Command '['C:\\Panda3D-1.10.0-x64\\python\\python.exe', '-B', 'build.py']' returned non-zero exit status 1
 WARNING: Removing obsolete parameter 'vc_version', is now auto-detected.
WARNING: Removing obsolete parameter 'use_lib_eigen', is now auto-detected.
Creating directory C:\Render\rpcore\native\scripts\..\win_amd64_panda1.10.0_py27_vc100
Executing command:  cmake C:/Render/rpcore/native -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_EXECUTABLE:STRING=C:\Panda3D-1.10.0-x64\python\python.exe -DPROJECT_NAME:STRING=native_ -DINTERROGATE_LIB:STRING=libp3interrogatedb -GVisual Studio 10 2010 Win64 -DPYTHONVER:STRING=27 -DHAVE_LIB_EIGEN=TRUE -DHAVE_LIB_BULLET=TRUE -DHAVE_LIB_FREETYPE=TRUE -DIGATE_VERBOSE=0 -DOPTIMIZE=3

-- Found Windows SDK v7.1: C:\Program Files\Microsoft SDKs\Windows\v7.1\
-- The C compiler identification is MSVC 16.0.30319.1
-- The CXX compiler identification is MSVC 16.0.30319.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Bitness: 64 bit ('1')
-- Detected panda3d installation: C:\Panda3D-1.10.0-x64
-- Detected visual studio version: vc10
-- Detected thirdparty directory: C:\Panda3D-1.10.0-x64/thirdparty/win-libs-vc10-x64
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Render/rpcore/native/win_amd64_panda1.10.0_py27_vc100
Executing command:  cmake --build . --config RelWithDebInfo -- /m

Microsoft (R) Verso do Mecanismo de Compilao 4.6.1586.0
[Microsoft .NET Framework, Verso 4.0.30319.42000]
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

Compilao de 15/01/2017 12:14:28 iniciada.
     1>Projeto "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\ALL_BUILD.vcxproj" no n 1 (destinos padro).
     1>O projeto "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\ALL_BUILD.vcxproj" (1) est compilando "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\ZERO_CHECK.vcxproj" (2) no n 1 (destinos padro).
     2>PrepareForBuild:
         Criando o diretrio "x64\RelWithDebInfo\ZERO_CHECK\".
       InitializeBuildStatus:
         Criando "x64\RelWithDebInfo\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
       CustomBuild:
         Checking Build System
         CMake does not need to re-run because C:/Render/rpcore/native/win_amd64_panda1.10.0_py27_vc100/CMakeFiles/generate.stamp is up-to-date.
       FinalizeBuildStatus:
         Excluindo o arquivo "x64\RelWithDebInfo\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild".
         Tocando "x64\RelWithDebInfo\ZERO_CHECK\ZERO_CHECK.lastbuildstate".
     2>Projeto de compilao pronto "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\ZERO_CHECK.vcxproj" (destinos padro).
     1>O projeto "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\ALL_BUILD.vcxproj" (1) est compilando "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\native_.vcxproj" (3) no n 2 (destinos padro).
     3>PrepareForBuild:
         Criando o diretrio "native_.dir\RelWithDebInfo\".
         Criando o diretrio "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\RelWithDebInfo\".
       InitializeBuildStatus:
         Criando "native_.dir\RelWithDebInfo\native_.unsuccessfulbuild" porque "AlwaysCreate" foi especificado.
       CustomBuild:
         Building Custom Rule C:/Render/rpcore/native/CMakeLists.txt
         CMake does not need to re-run because C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\CMakeFiles\generate.stamp is up-to-date.
       ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\x86_amd64\CL.exe /c /I"C:\Panda3D-1.10.0-x64\thirdparty\win-libs-vc10-x64\bullet\include" /I"C:\Panda3D-1.10.0-x64\thirdparty\win-libs-vc10-x64\eigen\include" /I"C:\Panda3D-1.10.0-x64\thirdparty\win-libs-vc10-x64\freetype\include" /I"C:\Panda3D-1.10.0-x64\thirdparty\win-libs-vc10-x64\freetype\include\freetype2" /I"C:\Panda3D-1.10.0-x64\include" /I"C:\Panda3D-1.10.0-x64\python\include" /IC:\Render\rpcore\native\source /Zi /nologo /W3 /WX- /MP /O2 /Ob2 /Oi /Ot /D WIN32 /D _WINDOWS /D WIN64_VC /D WIN64 /D WIN32_VC /D WIN32 /D EIGEN_MPL2_ONLY= /D EIGEN_NO_DEBUG= /D EIGEN_NO_STATIC_ASSERT= /D _HAS_EXCEPTIONS=0 /D PB_MODULE=native_ /D PB_CFG_MODULE=native_ /D "CMAKE_INTDIR=\"RelWithDebInfo\"" /D native__EXPORTS /D _WINDLL /D _MBCS /Gm- /EHsc /MD /GS- /fp:fast /Zc:wchar_t /Zc:forScope /GR- /Fo"native_.dir\RelWithDebInfo\\" /Fd"native_.dir\RelWithDebInfo\vcWindows7.1SDK.pdb" /Gd /TP /wd4996 /wd4275 /wd4267 /wd4101 /wd4273 /errorReport:queue ..\source\config_rsnative.cpp ..\source\gpu_command.cpp ..\source\gpu_command_list.cpp ..\source\ies_dataset.cpp ..\source\internal_light_manager.cpp ..\source\interrogate_module.cpp ..\source\interrogate_wrapper.cpp ..\source\pssm_camera_rig.cpp ..\source\pssm_helper.cpp ..\source\rp_light.cpp ..\source\rp_point_light.cpp ..\source\rp_spot_light.cpp ..\source\shadow_atlas.cpp ..\source\shadow_manager.cpp ..\source\shadow_source.cpp ..\source\tag_state_manager.cpp  /favor:blend /bigobj /Zm300
         config_rsnative.cpp
         gpu_command.cpp
         gpu_command_list.cpp
         ies_dataset.cpp
         internal_light_manager.cpp
         interrogate_module.cpp
         interrogate_wrapper.cpp
         pssm_camera_rig.cpp
         pssm_helper.cpp
         rp_light.cpp
         rp_point_light.cpp
         rp_spot_light.cpp
         shadow_atlas.cpp
         shadow_manager.cpp
         shadow_source.cpp
         tag_state_manager.cpp
       ManifestResourceCompile:
         C:\Program Files\Microsoft SDKs\Windows\v7.1\bin\rc.exe /nologo /fo"native_.dir\RelWithDebInfo\native_.dll.embed.manifest.res" native_.dir\RelWithDebInfo\native__manifest.rc
       Link:
         C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\x86_amd64\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\RelWithDebInfo\native_.dll" /INCREMENTAL /NOLOGO /LIBPATH:"C:/Panda3D-1.10.0-x64/thirdparty/win-libs-vc10-x64/bullet/lib" /LIBPATH:"C:/Panda3D-1.10.0-x64/thirdparty/win-libs-vc10-x64/bullet/lib/RelWithDebInfo" /LIBPATH:"C:/Panda3D-1.10.0-x64/thirdparty/win-libs-vc10-x64/freetype/lib" /LIBPATH:"C:/Panda3D-1.10.0-x64/thirdparty/win-libs-vc10-x64/freetype/lib/RelWithDebInfo" /LIBPATH:"C:/Panda3D-1.10.0-x64/lib" /LIBPATH:"C:/Panda3D-1.10.0-x64/lib/RelWithDebInfo" kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\Panda3D-1.10.0-x64\python\libs\python27.lib" libpandabullet.lib libp3framework.lib libpanda.lib libpandaexpress.lib libp3dtool.lib libp3dtoolconfig.lib libp3direct.lib libp3interrogatedb.lib LinearMath.lib BulletCollision.lib BulletDynamics.lib BulletSoftBody.lib freetype.lib /MANIFEST /ManifestFile:"native_.dir\RelWithDebInfo\native_.dll.intermediate.manifest" /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /DEBUG /PDB:"C:/Render/rpcore/native/win_amd64_panda1.10.0_py27_vc100/RelWithDebInfo/native_.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Render/rpcore/native/win_amd64_panda1.10.0_py27_vc100/RelWithDebInfo/native_.lib" /MACHINE:X64 /DLL native_.dir\RelWithDebInfo\native_.dll.embed.manifest.res
         native_.dir\RelWithDebInfo\config_rsnative.obj
         native_.dir\RelWithDebInfo\gpu_command.obj
         native_.dir\RelWithDebInfo\gpu_command_list.obj
         native_.dir\RelWithDebInfo\ies_dataset.obj
         native_.dir\RelWithDebInfo\internal_light_manager.obj
         native_.dir\RelWithDebInfo\interrogate_module.obj
         native_.dir\RelWithDebInfo\interrogate_wrapper.obj
         native_.dir\RelWithDebInfo\pssm_camera_rig.obj
         native_.dir\RelWithDebInfo\pssm_helper.obj
         native_.dir\RelWithDebInfo\rp_light.obj
         native_.dir\RelWithDebInfo\rp_point_light.obj
         native_.dir\RelWithDebInfo\rp_spot_light.obj
         native_.dir\RelWithDebInfo\shadow_atlas.obj
         native_.dir\RelWithDebInfo\shadow_manager.obj
         native_.dir\RelWithDebInfo\shadow_source.obj
         native_.dir\RelWithDebInfo\tag_state_manager.obj  /machine:x64
     3>LINK : fatal error LNK1104: cannot open file 'LinearMath.lib' [C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\native_.vcxproj]
     3>Projeto de compilao pronto "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\native_.vcxproj" (destinos padro) -- FALHA.
     1>Projeto de compilao pronto "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\ALL_BUILD.vcxproj" (destinos padro) -- FALHA.

FALHA da compilao.

       "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\ALL_BUILD.vcxproj" (destino padro) (1) ->
       "C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\native_.vcxproj" (destino padro) (3) ->
       (Link destino) ->
         LINK : fatal error LNK1104: cannot open file 'LinearMath.lib' [C:\Render\rpcore\native\win_amd64_panda1.10.0_py27_vc100\native_.vcxproj]

    0 Aviso(s)
    1 Erro(s)

Tempo Decorrido 00:02:26.98`

This error occour into RP V1.3, downloaded today from RP master branch. 
After i found this error, i try build the older version into my older PC, the older version is 1.2, and he build normally a few months ago, but when i try to build, i give the same error.

**Comment by rdb** [comment]
This is a Bullet library.  Hmm, I'm not sure why the pipeline is trying to use Bullet, even though it doesn't use it.  Perhaps you can try adding `use_lib_bullet=0` to the `rpcore/native/config.ini` file?

**Comment by tobspr** [comment]
Ah, hm, I made some changes to the P3D module builder, which makes it link with bullet whenever it detects a panda version compiled with bullet.

However, given that it detects bullet, it should also be able to find bullet.

Did you copy the thirdparty directory to the correct locations? (That is, into the built folder)

**Comment by RodrigoMedeirosrRS** [comment]
Yes, before i found this error, the RP give-me the ThirdParty missing folder error. So i put the thirdparty folder into Panda's root instalation folder, and the related error occour's.

Here is my panda root folder:
![panda folder](https://cloud.githubusercontent.com/assets/7956669/21963287/fd602138-db16-11e6-9fe5-466647aa2e1e.png)

I add the use_lib_bullet=0 into config.ini, don't work.

**Comment by tobspr** [comment]
Can you try copying the thirdparty folder to your `built/` folder?

**Comment by RodrigoMedeirosrRS** [comment]
Right, rebuilding panda...

**Comment by tobspr** [comment]
You don't need to rebuild panda, you can simply rerun the render pipeline setup :)

**Comment by RodrigoMedeirosrRS** [comment]
yes, i try to use the installed version of panda (Panda3D-SDK-1.10.0pre-e124205-x64.exe) and i delete my built folder :P

so i need rebuilt-it :D

**Comment by rdb** [comment]
The installed version should work fine.

You may need to copy LinearMath_x64.lib to LinearMath.lib (same for the other libs) in the `thirdparty/win-libs-vc10-x64/bullet/lib` directory for module finder to find it correctly.

**Comment by RodrigoMedeirosrRS** [comment]
Ok, i belive i found the problem! I have installed only the x64 thirdparty, because my Panda Version is x64. But the RP are asking to me the x32 libraries.
So i only rename all the lib's file (removing the x64 mention), and all is working now.

**Comment by RodrigoMedeirosrRS** [comment]
The RP really need the x32 libaries? I can use only x64?

**Comment by rdb** [comment]
No, you don't need x32 libraries.  It's just an issue in the way the libraries are named.  The RenderPipeline still expects x64 libraries, but it doesn't expect them to have x64 in the nmae.

**Comment by RodrigoMedeirosrRS** [comment]
You are right, thanks for the suggestion ;)
