### ISSUE TITLE
RP Crashing with AMD Crossfire

### ISSUE THREAD

**Issue by RodrigoMedeirosrRS** [tobspr/RenderPipeline#72]
Hello, recently i made a upgrade on my to get more performance on RP. Now mi system config is:

APU: A10 7890k
GPU: Radeon R7 250
RAM: HyperX 16gb (2x8) 1866mhz

So i am using a Crossfire between APU and GPU, but when i try to run the RP into this config, the apliccation won't start.

**Comment by tobspr** [comment]
Hi!

I don't think panda3d supports crossfire at the moment. Can you try verifying that the panda3d samples run properly?

Best regards,
Tobias

**Comment by rdb** [comment]
@tobspr I don't think there's anything in Panda that would prevent it from working.  I thought these technologies were implemented under the hood at the driver level.

**Comment by RodrigoMedeirosrRS** [comment]
Tobspr is right, the problem is into panda, no samples is running. But o belive i found the origin of error and part of problem is into panda3D and part is into Crossfire Technology:

http://support.amd.com/en-us/kb-articles/Pages/How-to-Configure-AMD-CrossFire-Using-AMD-Radeon-Settings.aspx

"AMD CrossFire™ is a technology which can combine up to four GPUs to speed up the rendering of 3D graphics. In AMD CrossFire setups, all display outputs are connected to the primary (master) card and outputs on the slave card(s) are disabled. AMD CrossFire™ only works in full screen mode.

Note! AMD CrossFire does not operate in applications running in Windowed mode. "

All applications into panda, EVERY start's into window mode, the only to fix it, is add an option indo Showbase start, to give us a option to start the engine into fullscreen.

**Comment by rdb** [comment]
What about just adding `fullscreen true` to the Config.prc file? Does that work?

**Comment by RodrigoMedeirosrRS** [comment]
No, not work, this is the only return of panda:

C:\Panda3D-1.10.0-x64\samples\carousel>"python" c:/Panda3D-1.10.0-x64/samples/carousel/main.py
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)

C:\Panda3D-1.10.0-x64\samples\carousel>

**Comment by RodrigoMedeirosrRS** [comment]
http://gpuopen.com/amd-crossfire-api/

**Comment by rdb** [comment]
This must be a driver bug, not a deficiency in Panda.  Can you run other OpenGL applications correctly?
