### ISSUE TITLE
Issues building the native modules

### ISSUE THREAD

**Issue by rcarjan** [tobspr/RenderPipeline#78]
Hello,
 I am trying to setup the RenderPipeline on my machine running Ubuntu Gnome 17.04. However I ran into some issues while building the native modules. 
I am unsure if this is a RenderPipeline issue, or a Panda3D issue, so I am hoping that posting this here, someone might be able to help me. I have tried solving the issue myself, but to no avail.

This is what the script outputs:

```
[ 04 ]  Building the native code .. (This might take a while!)
	Running script: rpcore/native/build.py




------------------------------------------------------------

CMake Error:


------------------------------------------------------------




Failed to execute 'build.py'
Output: Command '['/usr/bin/python', '-B', 'build.py']' returned non-zero exit status 255 
 Creating directory /home/radu/Projects/Panda3D-RenderPipeline/rpcore/native/scripts/../linux_amd64_panda1.10.0_py27
Executing command:  cmake /home/radu/Projects/Panda3D-RenderPipeline/rpcore/native -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_EXECUTABLE:STRING=/usr/bin/python -DPROJECT_NAME:STRING=native_ -DINTERROGATE_LIB:STRING=p3interrogatedb -DPYTHONVERDOT:STRING=2.7 -DHAVE_LIB_EIGEN=TRUE -DIGATE_VERBOSE=0 -DOPTIMIZE=3 

-- Bitness: 32 bit ('')
CMake Error at CMakeLists.txt:266 (message):
  Interrogate failed: Executing command: /usr/bin/interrogate -fnames -string
  -refcount -assert -python-native -S/usr/include/panda3d/parser-inc
  -S/usr/include/panda3d/ -srcdir .  -oc interrogate_wrapper.cpp -od
  interrogate.in -module native_ -library native_ -nomangle -DINTERROGATE
  -DCPPPARSER -D__STDC__=1 -D__cplusplus=201103L -D__attribute__\(x\)=
  -D__i386__ ./rp_spot_light.h ./tag_state_manager.h ./shadow_manager.h
  ./gpu_command_list.h ./rp_light.h ./shadow_source.h ./config_rsnative.h
  ./gpu_command.h ./internal_light_manager.h ./pssm_helper.h
  ./rp_point_light.h ./ies_dataset.h ./pointer_slot_storage.h
  ./pssm_camera_rig.h ./shadow_atlas.h

  

  /usr/include/panda3d/mutexPosixImpl.h:43:10: error: unknown type
  'pthread_mutex_t'

    INLINE pthread_mutex_t *get_posix_lock();
           ^~~~~~~~~~~~~~~

  /usr/include/panda3d/mutexPosixImpl.h:46:3: error: unknown type
  'pthread_mutex_t'

    pthread_mutex_t _lock;
    ^~~~~~~~~~~~~~~

  /usr/include/panda3d/mutexPosixImpl.h:71:10: error: unknown type
  'pthread_mutex_t'

    INLINE pthread_mutex_t *get_posix_lock();
           ^~~~~~~~~~~~~~~

  /usr/include/panda3d/mutexPosixImpl.h:74:3: error: unknown type
  'pthread_mutex_t'

    pthread_mutex_t _lock;
    ^~~~~~~~~~~~~~~

  /usr/include/panda3d/mutexPosixImpl.I:65:8: error: unknown type
  'pthread_mutex_t'

  INLINE pthread_mutex_t *MutexPosixImpl::

         ^~~~~~~~~~~~~~~

  /usr/include/panda3d/mutexPosixImpl.I:134:8: error: unknown type
  'pthread_mutex_t'

  INLINE pthread_mutex_t *ReMutexPosixImpl::

         ^~~~~~~~~~~~~~~

  /usr/include/panda3d/memoryHook.h:43:42: error: syntax error, unexpected
  IDENTIFIER, expecting ')'

    virtual void *heap_alloc_single(size_t size);
                                           ^~~~

  Error parsing file: './rp_spot_light.h'

   Traceback (most recent call last):
    File "scripts/interrogate.py", line 135, in <module>
      interrogate()
    File "scripts/interrogate.py", line 108, in interrogate
      try_execute(*cmd)
    File "/home/radu/Projects/Panda3D-RenderPipeline/rpcore/native/scripts/common.py", line 216, in try_execute
      raise Exception("Process had non-zero returncode:", process.returncode)

  Exception: ('Process had non-zero returncode:', 1)



-- Configuring incomplete, errors occurred!
See also "/home/radu/Projects/Panda3D-RenderPipeline/rpcore/native/linux_amd64_panda1.10.0_py27/CMakeFiles/CMakeOutput.log".




It seems the setup failed, do you want to open the troubleshooting page for this step? (y/n):
```

P.S: When running the terrain sample with the fallback modules(python), it looks like in the attached screenshot. Is there an issue with the sample, or is this how the fallback module should look? The others look and run just fine.

![screenshot from 2017-04-18 22-16-45](https://cloud.githubusercontent.com/assets/3381102/25148786/ce793c4e-2484-11e7-9f6b-95c569231f97.png)

P.P.S: When running the setup script, this error pops up every once in a while. Is there any way to solve this?
`JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock`

**Comment by rdb** [comment]
Could you state which exact version of Panda you have?  Knowing what drivers you have would help, too.

**Comment by rcarjan** [comment]
Regarding the panda version, it's the latest version to download as of today: [panda3d1.10_1.10.0~dev1106~zesty_amd64](https://www.panda3d.org/download.php?platform=zesty&version=devel&sdk)

As for the drivers, I have only installed the nvidia proprietary drivers:

```
Tue Apr 18 22:34:09 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 381.09                 Driver Version: 381.09                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 940M        Off  | 0000:01:00.0     Off |                  N/A |
| N/A   40C    P0    N/A /  N/A |    254MiB /  2002MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1057    G   /usr/lib/xorg/Xorg                              16MiB |
|    0      1572    G   /usr/lib/xorg/Xorg                              76MiB |
|    0      1796    G   /usr/bin/gnome-shell                            46MiB |
|    0      2214    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    85MiB |
+-----------------------------------------------------------------------------+

```

Linux version: 
`uname -a: Linux radu-ubuntu 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by castiel520** [comment]
@rdb I've met the same error under ubuntu 16.04 with native build

**Comment by rcarjan** [comment]
@castiel520 I have managed to solve this issue by building my own panda3d, and changing the build script a little.

What I did was edit the makepanda.py script, replacing both instances of "-pthread" with "-lpthread": [here](https://github.com/panda3d/panda3d/blob/master/makepanda/makepanda.py#L1277) and [here](https://github.com/panda3d/panda3d/blob/master/makepanda/makepanda.py#L1704)
It seems that when compiling with -pthread won't work, i'm not sure why. 

Regarding this error:
`
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
`
I'm still not sure what caused it, but it seems to compile and work OK even with this message popping up every few seconds, so I guess it's not that important.

**Comment by castiel520** [comment]
@rcarjan thanks for you reply!

unfortunately your solution does not work for me, i still got the same error.
here is what I did:

- uninstall the prebuild version of panda3d and get from latest master, replacing both instances of "-pthread" with "-lpthread" as you suggested
- make panda3d*.deb and install it
- run setup.py still got the same issue.

have you change any build script in RenderPipeline?
thanks again!

**Comment by rcarjan** [comment]
@castiel520 No, sorry, this is the only change I have made.
Are you using python 2 or 3?
Have you installed all necessary dependencies?

**Comment by castiel520** [comment]
@rcarjan hi, I am using python 2, and I have installed all necessary dependencies.

today i tried re-build panda3d and render-pipeline yet still got the same error. But really thanks for your help:)

**Comment by mpbagot** [comment]
I had the same problem, you have to change the read permissions of the files in /usr/include/panda3d. By default, the interrogate script cant read them and it causes the build to fail. Either run chmod or chown on the folders contents and re-run the render pipeline build. That should fix it.

Hope that helps.
