### ISSUE TITLE
Unable to create GLSL compute shader on intel integrated graphics

### ISSUE THREAD

**Issue by fr3nzy** [tobspr/RenderPipeline#79]
Hi

I'm attempting to install Render Pipeline on an integrated intel gpu - Intel Ivybridge Mobile.

```
-------------------------------------------------------------------------------`

Render Pipeline Setup 1.3

-------------------------------------------------------------------------------


[ 01 ]  Checking Panda3D Modules


[ 02 ]  Checking requirements ..
	Running script: data/setup/check_requirements.py


The C++ modules of the pipeline are faster and produce better 
results, but we will have to compile them. As alternative, 
a Python fallback is used, which is slower and produces worse 
results. Also some plugins only partially work with the python 
fallback (e.g. PSSM). Do you want to compile the C++ modules? (y/n): y


[ 03 ]  Downloading the module builder ...
	Running script: rpcore/native/update_module_builder.py
	Downloading:   0.00  B/s |                               |  0%   ETA:  --:--:-- Downloading:  92.82 GB/s |################################|100%   Time: 0:00:00


[ 04 ]  Building the native code .. (This might take a while!)
	Running script: rpcore/native/build.py


[ 05 ]  Generating .txo files ...
	Running script: data/generate_txo_files.py


[ 06 ]  Filtering default cubemap ..
	Running script: data/default_cubemap/filter.py
:display:gsg:glgsg(error): Could not create a GLSL compute shader.
Assertion failed: do_has_ram_mipmap_image(cdata, n) at line 4948 of panda/src/gobj/texture.cxx
Traceback (most recent call last):
  File "filter.py", line 105, in <module>
    Application()
  File "filter.py", line 93, in __init__
    dest_cubemap.write(join(filter_dir, "{}-#.png".format(mipmap)), 0, 0, True, False)
AssertionError: do_has_ram_mipmap_image(cdata, n) at line 4948 of panda/src/gobj/texture.cxx
Failed to execute 'filter.py'
Output: Command '['/usr/bin/python', '-B', 'filter.py']' returned non-zero exit status 1 
 Filtering mipmap 0
 Extracting data ..
 Writing data ..




It seems the setup failed, do you want to open the troubleshooting page for this step? (y/n):  n

Setup failed:	 Python script didn't return properly!

Please fix the above errors and then restart the setup.
```

I've tried reinstalling drivers, updating and removing them, to no avail. 
I'm using Panda 1.10 with the latest version of render pipeline.

Any idea what the issue is, any way to solve it?
_Thanks!_

**Comment by rdb** [comment]
Ivy Bridge is limited to OpenGL 4.0 and does not support compute shaders.

**Comment by fr3nzy** [comment]
What about Mesa 17.0.2? Apparently it has support for OpenGL 4.5;
https://www.mesa3d.org/relnotes/17.0.2.html

**Comment by rdb** [comment]
Are you on Linux?  I had assumed you were on Windows.

**Comment by fr3nzy** [comment]
yes Linux..

I installed the mesa 17.0.2 drivers which supposedly have support for OpenGL 4.5.
Unfortunately it turns out that isn't really the case.

Slightly different error running the script again:
```
[ 06 ]  Filtering default cubemap ..
	Running script: data/default_cubemap/filter.py
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader filter.compute.glsl:
filter.compute.glsl:1(10): error: GLSL 4.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES
filter.compute.glsl:0(0): error: Compute shaders require GLSL 4.30 or GLSL ES 3.10
Assertion failed: do_has_ram_mipmap_image(cdata, n) at line 4948 of panda/src/gobj/texture.cxx
Traceback (most recent call last):
  File "filter.py", line 105, in <module>
    Application()
  File "filter.py", line 93, in __init__
    dest_cubemap.write(join(filter_dir, "{}-#.png".format(mipmap)), 0, 0, True, False)
AssertionError: do_has_ram_mipmap_image(cdata, n) at line 4948 of panda/src/gobj/texture.cxx
Failed to execute 'filter.py'
```

**Comment by rdb** [comment]
I don't think so.  From the Mesa 17 release notes:

     - OpenGL 4.5 support on Haswell hardware

I saw mention of OpenGL 4.0 for Ivy Bridge in Mesa 17, but not anything implying compute shaders for Ivy Bridge.

If you find a version of Mesa and your drivers that do support compute shaders, you could try putting this in Config.prc:

    gl-version 4 0

This might be necessary to let the driver know that Panda will only be using OpenGL 3.2+ features.  It will only work on a recent master build of Panda.

**Comment by severin-lemaignan** [comment]
Same issue here, using mesa 18.

Relevant `glxinfo` details:
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)  (0x1616)
    Version: 18.0.0
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
```

It seems panda is using the compat profile instead of the core profile. I've added `gl-version 4 0` to `config/panda3d-config.prc`, but `setup.py` still fails with the same error (GLSL 4.3 not supported).

**Comment by RomanSC** [comment]
Hey all,

Having a similar issue, however, I'm able to run setup.py without errors by editing config.prc in the library itself not my projects local config.prc. For me (under python virtualenv) I am able to set gl-version in ./env/lib/python3.6/site-packages/panda3d/etc/Config.prc

In my project I have ./config/config.prc but it seems to be ignored for now. (Probably an issue with my code.) So maybe @severin-lemaignan is having the same issue there

I've tried:
gl-version 4 0
gl-version 4 3
gl-version 3 1
gl-version 3 2

All of them result in zero shadows in my game. The 3D environment is just plain gray

Here's my glxinfo:

```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)  (0x1916)
    Version: 18.0.4
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```
Also:
```
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.4
```

CPU is an i5-6200U with Intel Graphics 520 on Arch Linux OS

How do we tell Panda3d or Render Pipeline to use the correct version?

**Comment by rdb** [comment]
You can fix this by adding this to the Config.prc file that ships with the Panda3D installation:
```
gl-version 4 3
```
Don't forget to take it back out again after running `setup.py`.  You may also want to add it to the prc file in the `config` directory of the RenderPipeline so that it will take effect when running the pipeline itself.
