### ISSUE TITLE
Scattering: Larger atmosphere height does not color geometry

### ISSUE THREAD

**Issue by croxis** [tobspr/RenderPipeline#8]
Atmosphere height of 100: http://imgur.com/Xg7KFKz
Effects probably from underlying geometry poking through

Atmosphere height of 150: http://imgur.com/lcBx6lT
Scattering only view: http://imgur.com/L5nkmQQ

Scattering Settings: radiusGround = 6371
radiusAtmosphere = 6471 or 6521
offset = 0, 6371*2, 0

Mesh is a tessellated sphere with a radius of 6371

**Comment by tobspr** [comment]
Thats an issue with the geometry not being tesselated enough, it should be fixed with a higher tesselated geometry
