### ISSUE TITLE
Could not import Panda3D modules.

### ISSUE THREAD

**Issue by eddsys1977** [tobspr/RenderPipeline#81]
Hi! I'm trying to run the 'setup.py' but the process don't works on W7 with all the 'Panda3D-1.9.4' and 'RenderPipeline' Path variables in place and both Python 2.7.13 and 3.5.2 versions...

Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
=========== RESTART: C:\Panda3D-1.9.4\RenderPipeline-2.0\setup.py ===========
-------------------------------------------------------------------------------

Render Pipeline Setup 1.3

-------------------------------------------------------------------------------

[ 01 ]  [36m[1mChecking Panda3D Modules[0m

Could not import Panda3D modules! Please make sure they are 
on your path, and you are using the correct python version!

[31m[1mSetup failed:	[0m Failed to import Panda3D modules
[31m[1m
Please fix the above errors and then restart the setup.
[0m
>>>

**Comment by rdb** [comment]
The pipeline does not work with Panda 1.9.4.  Download a development build of Panda 1.10, and run setup.py using "ppython", which is guaranteed to point to Panda's installation of Python.

**Comment by eddsys1977** [comment]
Hi! It's working now! Thank you!
