### ISSUE TITLE
ImportError: /usr/share/panda3d/rpcore/native/native_.so

### ISSUE THREAD

**Issue by Jimbow500** [tobspr/RenderPipeline#83]
I'm still new to most to all of this, but I can't get RP to run.
I dropped the render pipeline files with Panda3D and had it originally in its own subfolder with a link to the rpcore folder. Still got the same error.

All files are in "/usr/share/pand3d"

`python main.py 
[>] CORE                      Using native core module 
Traceback (most recent call last):
  File "main.py", line 315, in <module>
    w = World().run()
  File "main.py", line 69, in __init__
    from rpcore import RenderPipeline, SpotLight
  File "/usr/share/panda3d/rpcore/__init__.py", line 32, in <module>
    from rpcore.render_pipeline import RenderPipeline
  File "/usr/share/panda3d/rpcore/render_pipeline.py", line 47, in <module>
    from rpcore.native import TagStateManager, PointLight, SpotLight
  File "/usr/share/panda3d/rpcore/native/__init__.py", line 77, in <module>
    from rpcore.native import native_ as _native_module  # pylint: disable=wrong-import-position
ImportError: /usr/share/panda3d/rpcore/native/native_.so: undefined symbol: _Z16LookupNamedClassRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

**Comment by rdb** [comment]
Which exact version of Panda are you using?

**Comment by Jimbow500** [comment]
I'm using "panda3d1.10_1.10.0~dev1184~xenial_amd64" on Mint 18.2

**Comment by Jimbow500** [comment]
I'm still having an import error after reinstalling and trying different links

**Comment by rdb** [comment]
This seems like it might be a C++11 setting mismatch.  Although modulebuilder does pass `-std=c++11`, hmm.

Have you used the RenderPipeline in the past?  Could there be some conflict with a previous version of the RenderPipeline modules that were still installed in your system?

**Comment by Jimbow500** [comment]
@rdb I tried to remove everything that was installed via terminal, then deleting /usr/share/panda3d and renderpipeline files. Reinstalled everything again as it was a fresh start and still got the same error. I may have missed some files when deleting.

**Comment by Jimbow500** [comment]
I tried to move RP into a subfolder inside of a project. Redirected the project to use those files. I'm still getting the same errors

**Comment by Jimbow500** [comment]
[https://i.imgur.com/euMnxgA.png](url)

**Comment by Jimbow500** [comment]
I didn't mean to do that oops

**Comment by Jimbow500** [comment]
@rdb on line 77 in __init__ I just comment the else: script so it just uses the other one and everything is working correctly now
