### ISSUE TITLE
Error in Erin Bruneton copy_inscatter.glsl code

### ISSUE THREAD

**Issue by GarryGuanDoubleG** [tobspr/RenderPipeline#85]
https://github.com/tobspr/RenderPipeline/blob/master/rpplugins/scattering/shader/eric_bruneton/copy_inscatter.compute.glsl

line 42: `    vec3 mie = texelFetch(deltaSRSampler, ivec3(coord, layer), 0).xyz;`
should be `    vec3 mie = texelFetch(deltaSMSampler, ivec3(coord, layer), 0).xyz;`

**Comment by tobspr** [comment]
Nice catch! Have you checked if this changes the rendering result?

**Comment by GarryGuanDoubleG** [comment]
It changes the intensity of the mie factor when the sun is setting. It's a lot more yellow & intense around the horizon just under the sun and the overall yellow area around the sun fades faster than if it were set to the deltaSRSampler. The sun disk is also more visible.
