### ISSUE TITLE
RP crashing

### ISSUE THREAD

**Issue by PGaming6994** [tobspr/RenderPipeline#86]
Hi, i'm attempting to use RenderPipeline but i have an issue. I've read where it could be the Visual Studio install but it seems to of compiled fine (according to the setup) but upon running it loads some stuff and crashes. Here's an image: https://gyazo.com/bb2db2ca6542d85fc454d98e6136e813 this is using the Roaming Ralph sample. Non RP samples do run however. GPU used was Intel HD 4600 (NVIDIA 740M uninstalled itself!!)

**Comment by PGaming6994** [comment]
I'd like to add, with 740M it does more, but i get a traceback. Any suggestions? https://gyazo.com/ab34baf4256b245aa4ce1ac8ca706fb6

**Comment by rdb** [comment]
Seems to be a regression in Panda3D.  I'm on the case.

**Comment by PGaming6994** [comment]
@rdb any luck? i'm willing to test anything.

**Comment by PGaming6994** [comment]
all fixed! slightly slower than i anticipated but i am testing over Teamviewer atm.
