### ISSUE TITLE
setup.py thinks I don't have panda3d installed?

### ISSUE THREAD

**Issue by RomanSC** [tobspr/RenderPipeline#88]
Hi, first off this looks amazing, thanks for making it, I can't wait to use it.

Edit: 

Operating System: Arch Linux

I'm having trouble getting started though. I've compiled and installed panda3d at ~/.local/lib/python3.6/site-packages (the git version found here: https://github.com/panda3d/panda3d)

setup.py 'asks' whether panda3d is installed by:

```
    try:
        from panda3d.core import NodePath
    except ImportError:
        print("\n")
        print("Could not import Panda3D modules! Please make sure they are ")
        print("on your path, and you are using the correct python version!")
        error("Failed to import Panda3D modules")
```

With the version of panda installed from git, I don't have panda3d.core.NodePath ... 

I compiled using this:

```
export DESTDIR=/home/roman/.local/lib/python3.6/site-packages/
export PYTHONPATH=/usr/bin/python3 
export LD_LIBRARY_PATH=/home/roman/.local/lib/python3.6/site-packages/

python makepanda/makepanda.py --everything --installer --no-egl --no-gles --no-gles2 --no-opencv --threads=16

python makepanda/makewheel.py
python makepanda/installpanda.py
```
How should I compile panda3d to get NodePath so that I can use render_pipeline?

Thank you

Edit:

Here's output for setup.py
```
$ python setup.py

-------------------------------------------------------------------------------

Render Pipeline Setup 1.3

-------------------------------------------------------------------------------


[ 01 ]  Checking Panda3D Modules


Could not import Panda3D modules! Please make sure they are 
on your path, and you are using the correct python version!

Setup failed:	 Failed to import Panda3D modules

Please fix the above errors and then restart the setup.
```

**Comment by RomanSC** [comment]
Closing,

This was due to an incorrectly installed panda3d... If you check the PKGBUILD at: https://aur.archlinux.org/packages/panda3d-git/

You can see the it's labeled as 1.9xx but actually the PKGBUILD just installs the latest git version of Panda3D from github. So... on Arch Linux just install panda3d-git then run render_pipeline/setup.py

My bad.

**Comment by okaminoseishin** [comment]
To whom it may concern.
Check rules at `/usr/lib/python*.*/site-packages/panda3d` directory, they must be `755`.
If others can't read them, then you can't import module's content and error described above still occurs.

Especially if you alter default value of `umask` in `/etc/profile` in stronger direction.
