### ISSUE TITLE
Linux: Nothing renders with Bumblebee + NVIDIA proprietary drivers

### ISSUE THREAD

**Issue by CommanderMushu** [tobspr/RenderPipeline#91]
This is probably a hyper-specific issue, but I figured I'd report it anyway.

I'm attempting to run RenderPipeline on a Linux laptop running Bumblebee and using the NVIDIA proprietary drivers, but all that renders is a black screen. I've tested this with multiple samples and my own test applications. RenderPipeline reports no errors, and Panda3d behaves normally otherwise.

Currently the Nouveau drivers do not function with Bumblebee for certain newer NVIDIA graphics cards. As such they cannot be substituted in this scenario.

What is Bumblebee?
> Bumblebee is an effort to make NVIDIA Optimus enabled laptops work in GNU/Linux systems. Such feature involves two graphics cards with two different power consumption profiles plugged in a layered way sharing a single framebuffer.

Basically it's for laptops with both integrated and discrete graphics. I am unable to disable integrated graphics in my BIOS/UEFI, so in order to use my discrete GPU at all I must use Bumblebee.

## System Information

**Panda3d Version**: 1.10.0 (development build)
**Python Version**: 3.6
**OpenGL Version**: 4.6
**NVIDIA Driver Version**: 390.25-14
**Bumblebee Version**: 3.2.1
**GPU**: NVIDIA GTX 950m (NV110 Maxwell)

**OS Info**
NAME="Antergos Linux"
VERSION="18.3-Minimal-ISO-Rolling"
ID=antergos
ID_LIKE=arch
ARCHITECTURE=64-bit

## Output from RenderPipeline

> [>] CORE                      Using panda3d-supplied core module
[>] RenderPipeline            Using Python 3.6 with architecture linux_amd64 
[>] RenderPipeline            Using Panda3D 1.10.0 built on Mar  2 2018 09:03:16 
[>] RenderPipeline            Using git commit 43914f4e758524f2583dd3bb60bc83529195dcb7 
[>] MountManager              Auto-Detected base path to /home/nick/Panda/Test/RenderPipeline 
[>] RenderPipeline            Mount manager was not mounted, mounting now ... 
[>] MountManager              Setting up virtual filesystem 
[>] MountManager              Mounting auto-detected config dir: /home/nick/Panda/Test/RenderPipeline/config/ 
[>] MountManager              Mounting ramdisk as /$$rptemp 
[>] RenderPipeline            No settings loaded, loading from default location 
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
:display(warning): FrameBufferProperties available less than requested.
  requested: depth_bits=1 red_bits=1 green_bits=1 blue_bits=1 alpha_bits=1 back_buffers=1 force_hardware 
  got: depth_bits=24 color_bits=24 red_bits=8 green_bits=8 blue_bits=8 alpha_bits=8 accum_bits=64 force_hardware force_software 
[>] RenderPipeline            Driver Version = 4.6.0 NVIDIA 390.25 
[>] RenderPipeline            Driver Vendor = NVIDIA Corporation 
[>] RenderPipeline            Driver Renderer = GeForce GTX 950M/PCIe/SSE2 
[>] RenderPipeline            Render resolution is 800 x 600 
[!] RPLoader                  Loading '/$$rp/data/gui/loading_screen_bg.txo' took 90.74 ms
[>] LightManager              Tile size = 24 x 16 , Num tiles = 34 x 38 
[>] GPUCommandQueue           Allocating command buffer of size 32768 
[>] GroupedInputBlock         Native UBO support = False 
[!] RPLoader                  Loading '/$$rp/data/default_cubemap/cubemap.txo' took 308.61 ms
[!] RPLoader                  Loading '/$$rp/data/builtin_models/skybox/skybox.txo' took 119.97 ms
[>] PluginManager             Loading plugin settings 
[>] PluginManager             Creating plugin instances .. 
[>] Debugger                  Creating debugger 
[>] plugin:scattering         Loading scattering method for 'eric_bruneton' 
[>] StageManager              Setup stages .. 
[>] StageManager              Preparing stages .. 
[>] AOStage                   Blur quality is MEDIUM 
[>] StageManager              Awaiting future pipe Exposure 
[>] UpdatePreviousPipesStage  Creating previous pipes stage .. 
[>] StageManager              Writing shader config 
[>] ScatteringMethodEricBruneton Precomputing ... 
[>] plugin:pssm               Initializing pssm .. 
[!] RPLoader                  Loading '/$$rp/rpplugins/bloom/resources/lens_dirt.txo' took 122.28 ms
[>] RenderPipeline            Finished initialization in 1.774 s, first frame: 3 
[>] RenderPipeline            Took 0.001 s until first frame 
[!] Panda3D                   :linmath(warning): Tried to invert singular LMatrix4.
[>] RenderPipeline            Hiding loading screen after 10 pre-rendered frames.

**Comment by CommanderMushu** [comment]
I'm an idiot.
https://github.com/tobspr/RenderPipeline/issues/76

I'm submitting a pull request to automatically handle systems running Bumblebee during `setup.py`

**Comment by CommanderMushu** [comment]
I also suck at git apparently. Instead of a pull request here's a file containing the changes I've made.
[setup.py.txt](https://github.com/tobspr/RenderPipeline/files/1780928/setup.py.txt)

**Comment by tobspr** [comment]
You can use the github online editor to easily make a new PR. 
I have looked at the file - I would prefer just adding a command line option, e.g. "--use-primusrun" or even better, something generic like "--python-runner=primusrun"
